target("tuesdays-core-utils")
    add_files("utils/**.cpp")
    add_includedirs(".")
    add_packages("imgui-sfml", "spdlog", { public = true })

target("tuesdays-core-engine")
    add_files("engine/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-utils")
    add_packages("imgui-sfml", "spdlog", { public = true })

target("tuesdays-core-globals")
    add_includedirs(".")
    add_packages("imgui-sfml", "spdlog", { public = true })

target("tuesdays-core-lifetimes")
    add_files("lifetimes/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-globals", "tuesdays-core-engine")
    add_packages("imgui-sfml", "spdlog", { public = true })

target("tuesdays-core-tasks")
    -- add_files("tasks/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-globals", "tuesdays-core-utils")
    add_packages("imgui", "spdlog", { public = true })

target("tuesdays-core-keys")
    add_files("keys/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-globals", "tuesdays-core-utils")
    add_packages("sfml", "spdlog", { public = true })

target("tuesdays-core-components")
    -- add_files("components/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-utils")
    add_packages("imgui", { public = true })

target("tuesdays-core-layers")
    add_files("layers/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-globals", "tuesdays-core-utils")
    add_packages("imgui", "spdlog", { public = true })
